Sample configs for ss+wss+web
v2fly/v2ray-examples pull request #15
Opened 2020-08-29 09:29 UTC by touamano

2020-08-29 13:05 UTC, offferu commented
能否增加个nginx.conf的设置范例，有些不是很清楚，特别是
"path": "/websocket", // 必须换成自定义的 PATH
这里的path地址要和nginx的location地址一致吗？多谢！

2020-09-26 15:13 UTC, DuckSoft requested changes
Good, except some small typos. Fix them to continue.

2020-09-26 15:13 UTC, DuckSoft commented on Shadowsocks-Websocket-Web-TLS/README - zh-CN.md
> +Passowrd: ifYouWantToKeepYourPassphraseSafeChangeThis!!
Password

2020-09-26 15:13 UTC, DuckSoft commented on Shadowsocks-Websocket-Web-TLS/README - zh-CN.md
> +Configure:
Configuration

2020-09-26 15:13 UTC, DuckSoft commented on Shadowsocks-Websocket-Web-TLS/README.md
> +Passowrd: ifYouWantToKeepYourPassphraseSafeChangeThis!!
同上

2020-09-26 15:13 UTC, DuckSoft commented on Shadowsocks-Websocket-Web-TLS/README.md
> +Configure...:
同上

2020-10-09 16:29 UTC, merged

2020-10-09 16:42 UTC, parasomn1a commented
I fixed them and merged (the PR has been quiet for a while

Not good at git and it's the first time to operate on this repository, tell me if I have any wrong operation.